### ISSUE TITLE
Question: possible to get most recent matches

### ISSUE THREAD

**Issue by Vrekt** [RobertoGraham/fortnite-2#6]
Was wondering if its possible to have a function for getting a players recent match? I know sites such as fortnite tracker are able to do this.

**Comment by RobertoGraham** [comment]
As far as I know sites like that capture your stats every 3 mins or so, check if there's a 1 match difference between captures and if so they can determine how many kills you got and what your score went up by for that match. My site does this at least. 3 mins is because that's how long a really short match + queueing would last. Maybe I will write a separate component that you can configure to watch a player's stats updates

**Comment by RobertoGraham** [comment]
I will close this issue and I have opened #7 to implement communication with the Friends API. I've seen this done for Fortnite clients for other languages so it shouldn't be too difficult
